// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB45qbhYieY8xzyVuAxzmkIZd8eWGNnGQ',
    appId: '1:214001320438:android:39d92f0cfb2e9ddd1607d7',
    messagingSenderId: '214001320438',
    projectId: 'air-quality-4b969',
    databaseURL: 'https://air-quality-4b969-default-rtdb.firebaseio.com',
    storageBucket: 'air-quality-4b969.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgzKiP9CxpLCuJrV1D1ZlMU2wB-G7WG7M',
    appId: '1:214001320438:ios:8b30a701236cd8a81607d7',
    messagingSenderId: '214001320438',
    projectId: 'air-quality-4b969',
    databaseURL: 'https://air-quality-4b969-default-rtdb.firebaseio.com',
    storageBucket: 'air-quality-4b969.appspot.com',
    iosClientId: '214001320438-l1fk11nqhpolc3rul992k4equ9pb06d1.apps.googleusercontent.com',
    iosBundleId: 'com.example.airQualityy',
  );
}
